name: Workflow containers
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  template-drift:
    uses: nwarila-platform/workflow-template-drift/.github/workflows/check.yaml@3ac6d2f3ce65e2f98963826e71ad9e79c5e43c09 # v3.0.0
